import React, { useState, useEffect } from "react";

export default function App() {
  const animals = [
    "Fox",
    "Wolf",
    "Cat",
    "Dog",
    "Rabbit",
    "Crow",
    "Raven",
    "Sparrow",
    "Owl",
    "Hawk",
    "Eagle",
    "Falcon",
    "Peacock",
    "Swan",
    "Duck",
    "Goose",
    "Chicken",
    "Rooster",
    "Turkey",
    "Pigeon",
    "Seagull",
    "Penguin",
    "Parrot",
    "Cockatoo",
    "Canary",
    "Flamingo",
    "Crane",
    "Heron",
    "Stork",
    "Kiwi",
    "Cassowary",
    "Ostrich",
    "Bat",
    "Butterfly",
    "Moth",
    "Bee",
    "Wasp",
    "Hornet",
    "Ant",
    "Spider",
    "Scorpion",
    "Dragonfly",
    "Grasshopper",
    "Cricket",
    "Beetle",
    "Ladybug",
    "Firefly",
    "Centipede",
    "Millipede",
    "Snail",
    "Slug",
    "Jellyfish",
    "Octopus",
    "Squid",
    "Cuttlefish",
    "Seal",
    "Sea Lion",
    "Walrus",
    "Dolphin",
    "Whale",
    "Shark",
    "Hammerhead Shark",
    "Tiger Shark",
    "Great White Shark",
    "Manta Ray",
    "Stingray",
    "Swordfish",
    "Tuna",
    "Salmon",
    "Koi Fish",
    "Goldfish",
    "Catfish",
    "Pufferfish",
    "Eel",
    "Seahorse",
    "Clownfish",
    "Angelfish",
    "Betta Fish",
    "Guppy",
    "Piranha",
    "Carp",
    "Barracuda",
    "Lobster",
    "Crab",
    "Hermit Crab",
    "Shrimp",
    "Krill",
    "Starfish",
    "Sea Urchin",
    "Otter",
    "Beaver",
    "Raccoon",
    "Panda",
    "Red Panda",
    "Bear",
    "Polar Bear",
    "Grizzly Bear",
    "Koala",
    "Sloth",
    "Monkey",
    "Chimpanzee",
    "Gorilla",
    "Orangutan",
    "Baboon",
    "Lemur",
    "Tiger",
    "Lion",
    "Leopard",
    "Jaguar",
    "Cheetah",
    "Panther",
    "Lynx",
    "Bobcat",
    "Cougar",
    "Hyena",
    "Jackal",
    "Coyote",
    "Deer",
    "Elk",
    "Moose",
    "Reindeer",
    "Goat",
    "Sheep",
    "Ram",
    "Cow",
    "Bull",
    "Buffalo",
    "Bison",
    "Yak",
    "Horse",
    "Donkey",
    "Zebra",
    "Camel",
    "Llama",
    "Alpaca",
    "Pig",
    "Boar",
    "Hedgehog",
    "Porcupine",
    "Mole",
    "Rat",
    "Mouse",
    "Hamster",
    "Guinea Pig",
    "Squirrel",
    "Flying Squirrel",
    "Chipmunk",
    "Ferret",
    "Mink",
    "Weasel",
    "Badger",
    "Wolverine",
    "Armadillo",
    "Anteater",
    "Tapir",
    "Hippo",
    "Rhino",
    "Elephant",
    "Giraffe",
    "Kangaroo",
    "Wallaby",
    "Possum",
    "Wombat",
    "Platypus",
    "Tasmanian Devil",
    "Crocodile",
    "Alligator",
    "Komodo Dragon",
    "Lizard",
    "Gecko",
    "Iguana",
    "Chameleon",
    "Snake",
    "Cobra",
    "Python",
    "Viper",
    "Anaconda",
    "Turtle",
    "Tortoise",
    "Frog",
    "Toad",
    "Salamander",
    "Axolotl",
    "Newt",
    "Phoenix",
    "Dragon",
    "Unicorn",
    "Griffin",
    "Cerberus",
    "Hydra",
    "Kraken",
    "Mermaid",
    "Basilisk",
    "Manticore",
    "Yeti",
    "Loch Ness Monster",
    "Kitsune",
    "Tanuki",
    "Bakeneko",
    "Nekomata",
    "Qilin",
    "Kirin",
    "Pegasus",
    "Wyvern",
    "Leviathan",
    "Cockatrice",
    "Siren",
    "Harpy",
    "Minotaur",
    "Centaur",
    "Satyr",
  ];
  // ===== ADD THIS UNDER recentAnimals =====

  const recentObjects: string[] = [];

  const getUniqueObject = () => {
    let available = objects.filter((object) => !recentObjects.includes(object));

    if (available.length === 0) {
      recentObjects.length = 0;
      available = objects;
    }

    const object = available[Math.floor(Math.random() * available.length)];

    recentObjects.push(object);

    if (recentObjects.length > 10) {
      recentObjects.shift();
    }

    return object;
  };

  const objects = [
    "Lantern",
    "Mask",
    "Umbrella",
    "Mirror",
    "Clock",
    "Book",
    "Bell",
    "Sword",
    "Ribbon",
    "Teacup",
    "Candle",
    "Fan",
    "Chains",
    "Key",
    "Flowers",
    "Music Box",
    "Camera",
    "Scissors",
    "Notebook",
    "Pen",
    "Pencil",
    "Brush",
    "Paint",
    "Bottle",
    "Potion",
    "Crystal",
    "Gem",
    "Ring",
    "Necklace",
    "Bracelet",
    "Crown",
    "Cape",
    "Hat",
    "Shoes",
    "Boots",
    "Gloves",
    "Helmet",
    "Armor",
    "Shield",
    "Spear",
    "Bow",
    "Arrow",
    "Gun",
    "Dagger",
    "Knife",
    "Axe",
    "Hammer",
    "Staff",
    "Wand",
    "Orb",
    "Dice",
    "Card",
    "Chess Piece",
    "Coin",
    "Wallet",
    "Bag",
    "Backpack",
    "Suitcase",
    "Map",
    "Compass",
    "Binoculars",
    "Telescope",
    "Microscope",
    "Phone",
    "Tablet",
    "Laptop",
    "Computer",
    "Keyboard",
    "Mouse",
    "Headphones",
    "Speaker",
    "Microphone",
    "Radio",
    "Television",
    "Monitor",
    "Controller",
    "Joystick",
    "Drone",
    "Robot",
    "Gear",
    "Pipe",
    "Valve",
    "Engine",
    "Battery",
    "Lightbulb",
    "Neon Sign",
    "Flashlight",
    "Torch",
    "Firework",
    "Bomb",
    "Rocket",
    "Satellite",
    "Spaceship",
    "Train",
    "Car",
    "Bike",
    "Motorcycle",
    "Boat",
    "Ship",
    "Anchor",
    "Wheel",
    "Ticket",
    "Passport",
    "Stamp",
    "Envelope",
    "Letter",
    "Scroll",
    "Poster",
    "Painting",
    "Frame",
    "Canvas",
    "Statue",
    "Doll",
    "Puppet",
    "Marionette",
    "Toy",
    "Plushie",
    "Balloon",
    "Bubble",
    "Snow Globe",
    "Hourglass",
    "Pocket Watch",
    "Calendar",
    "Diary",
    "Bookmark",
    "Photo",
    "Polaroid",
    "Film Reel",
    "Cassette",
    "Vinyl",
    "CD",
    "DVD",
    "Projector",
    "Typewriter",
    "Printer",
    "Stamp Pad",
    "Sticker",
    "Badge",
    "Medal",
    "Trophy",
    "Cane",
    "Crutch",
    "Wheelchair",
    "Mask",
    "Sunglasses",
    "Glasses",
    "Hairpin",
    "Comb",
    "Perfume",
    "Lipstick",
    "Mirror Compact",
    "Soap",
    "Towel",
    "Pillow",
    "Blanket",
    "Curtain",
    "Chair",
    "Table",
    "Desk",
    "Cabinet",
    "Shelf",
    "Drawer",
    "Bed",
    "Lamp",
    "Chandelier",
    "Window",
    "Door",
    "Fence",
    "Bridge",
    "Fountain",
    "Clock Tower",
    "Bird Cage",
    "Aquarium",
    "Terrarium",
    "Plant Pot",
    "Vase",
    "Bonsai",
    "Cactus",
    "Mushroom",
    "Feather",
    "Bone",
    "Skull",
    "Fossil",
    "Shell",
    "Pearl",
    "Coral",
    "Ice Cube",
    "Snowflake",
    "Cloud",
    "Star",
    "Moon",
    "Sun",
    "Planet",
    "Meteor",
    "Comet",
    "Galaxy",
    "Crystal Ball",
    "Tarot Card",
    "Ouija Board",
    "Dreamcatcher",
    "Totem",
    "Charm",
    "Talisman",
    "Seal Stamp",
    "Origami",
    "Paper Crane",
    "Kite",
    "Pinwheel",
    "Wind Chime",
    "Bellflower",
    "Lotus",
    "Cherry Blossom",
    "Rose",
    "Sunflower",
    "Lavender",
    "Violet",
    "Lily",
    "Daisy",
    "Tulip",
    "Hydrangea",
    "Spider Lily",
    "Maple Leaf",
    "Bamboo",
    "Pinecone",
    "Acorn",
    "Apple",
    "Orange",
    "Peach",
    "Strawberry",
    "Blueberry",
    "Cherry",
    "Grape",
    "Watermelon",
    "Cake",
    "Cookie",
    "Candy",
    "Chocolate",
    "Ice Cream",
    "Donut",
    "Cupcake",
    "Bread",
    "Croissant",
    "Pizza",
    "Burger",
    "Noodles",
    "Ramen",
    "Sushi",
    "Bento",
    "Teapot",
    "Coffee Cup",
    "Wine Glass",
    "Bottle Cap",
    "Fork",
    "Knife",
    "Spoon",
    "Plate",
    "Bowl",
    "Tray",
    "Cooking Pot",
    "Pan",
    "Oven",
    "Stove",
    "Refrigerator",
    "Safe",
    "Treasure Chest",
    "Lock",
    "Padlock",
    "Chain",
    "Rope",
    "Net",
    "Hook",
    "Fishing Rod",
    "Bucket",
    "Shovel",
    "Pickaxe",
    "Lantern Pole",
    "Street Sign",
    "Traffic Light",
    "Mailbox",
    "Telephone Booth",
    "Vending Machine",
    "ATM",
    "Escalator",
    "Elevator",
    "Clockwork Gear",
    "Steam Engine",
    "Cyber Chip",
    "Hologram",
    "Neon Tube",
    "Pixel Cube",
    "Glitch Screen",
    "Data Disk",
    "Memory Card",
    "USB Drive",
    "VR Headset",
    "AI Core",
    "Energy Sword",
    "Mechanical Arm",
    "Hoverboard",
    "Jetpack",
    "Magic Scroll",
    "Rune Stone",
    "Ancient Tablet",
    "Sacred Relic",
    "Golden Apple",
    "Silver Key",
    "Black Feather",
    "White Rose",
    "Red Thread",
    "Blue Flame",
    "Broken Sword",
    "Cracked Mask",
    "Glass Eye",
    "Artificial Heart",
    "Music Sheet",
    "Violin",
    "Piano",
    "Guitar",
    "Flute",
    "Drum",
    "Accordion",
    "Harp",
    "Trumpet",
    "Saxophone",
    "Megaphone",
    "Whistle",
    "Bell Necklace",
    "Fox Mask",
    "Kitsune Mask",
    "Festival Lantern",
    "Torii Gate",
    "Shrine Charm",
    "Prayer Beads",
    "Incense",
    "Tatami",
    "Shoji Screen",
    "Kimono Sleeve",
    "Katana",
    "Naginata",
    "Kunai",
    "Shuriken",
    "Potion Bottle",
    "Alchemy Flask",
    "Magic Crystal",
    "Floating Candle",
    "Spirit Lantern",
    "Moon Mirror",
    "Dream Bottle",
    "Star Pendant",
    "Cloud Ribbon",
    "Ink Bottle",
    "Calligraphy Brush",
    "Wax Seal",
    "Porcelain Doll",
    "Clockwork Bird",
    "Mechanical Fish",
    "Paper Umbrella",
    "Golden Crown",
    "Silver Bell",
    "Bone Crown",
    "Spider Web",
    "Crystal Flower",
    "Hanging Charm",
    "Wind Bell",
    "Raincoat",
    "Bandage Roll",
    "Medical Syringe",
    "Heartbeat Monitor",
    "Lab Coat",
    "Test Tube",
    "DNA Capsule",
    "Floating Book",
    "Ancient Key",
    "Ghost Candle",
    "Eclipse Orb",
    "Galaxy Jar",
    "Void Cube",
    "Shadow Cloak",
    "Light Halo",
    "Spirit Chain",
    "Magic Door",
    "Floating Island",
    "Moon Clock",
    "Star Compass",
    "Fantasy Map",
    "Dragon Egg",
    "Phoenix Feather",
    "Mermaid Pearl",
    "Unicorn Horn",
    "Griffin Claw",
    "Kraken Tentacle",
    "Hydra Fang",
    "Crystal Sword",
    "Lava Lamp",
    "Ice Crown",
    "Thunder Drum",
    "Storm Lantern",
    "Ocean Bottle",
    "Forest Totem",
    "Desert Relic",
    "Snow Globe",
    "Royal Cape",
    "Pirate Flag",
    "Knight Shield",
    "Samurai Helmet",
    "Cyber Visor",
    "Steampunk Goggles",
    "Dream Mirror",
    "Night Lamp",
    "Sun Pendant",
    "Moon Necklace",
    "Star Earrings",
    "Cloud Pillow",
    "Rose Crown",
    "Butterfly Pin",
    "Spider Ring",
    "Crow Feather",
    "Wolf Fang",
    "Cat Bell",
    "Rabbit Doll",
    "Shark Tooth",
    "Jellyfish Lamp",
  ];

  const themes = [
    "Japanese",
    "Cyberpunk",
    "Dreamcore",
    "Fantasy",
    "Ocean",
    "Royal",
    "Nature",
    "Festival",
    "Horror",
    "Space",
    "Vintage",
    "Steampunk",
    "Yokai",
    "Street Fashion",
    "Angel",
    "Demon",
    "Fairy",
    "Ghost",
    "Post-Apocalyptic",
    "Sci-Fi",
    "Medieval",
    "Victorian",
    "Gothic",
    "Dark Fantasy",
    "Light Fantasy",
    "Mythology",
    "Ancient Egypt",
    "Ancient Greece",
    "Ancient China",
    "Ancient Japan",
    "Samurai",
    "Ninja",
    "Pirate",
    "Knight",
    "Circus",
    "Carnival",
    "Casino",
    "Mafia",
    "Detective",
    "Military",
    "Desert",
    "Arctic",
    "Jungle",
    "Underwater",
    "Sky Kingdom",
    "Cloudcore",
    "Lovecraftian",
    "Witchcore",
    "Fairytale",
    "Fairycore",
    "Kidcore",
    "Weirdcore",
    "Voidcore",
    "Cottagecore",
    "Angelcore",
    "Devilcore",
    "Princesscore",
    "Royalcore",
    "Retro",
    "80s Neon",
    "90s Anime",
    "Y2K",
    "Techwear",
    "Street Punk",
    "Grunge",
    "Emo",
    "Pastel",
    "Monochrome",
    "Luxury",
    "Crystal",
    "Glass",
    "Porcelain",
    "Paper",
    "Ink",
    "Music",
    "Theater",
    "Opera",
    "Idol",
    "Magic Academy",
    "Alchemy",
    "Necromancer",
    "Celestial",
    "Solar",
    "Lunar",
    "Astrology",
    "Tarot",
    "Dreamwalker",
    "Nightmare",
    "Heaven",
    "Hell",
    "Forest Spirit",
    "Deep Sea",
    "Bioluminescent",
    "Toxic",
    "Radioactive",
    "Mechanical",
    "Clockwork",
    "Digital",
    "Glitch",
    "Virtual Reality",
    "Arcade",
    "Zombie",
    "Vampire",
    "Werewolf",
    "Haunted Mansion",
  ];

  const colors = [
    "Red",
    "Blue",
    "Yellow",
    "Green",
    "Orange",
    "Purple",
    "Pink",
    "Black",
    "White",
    "Gray",
    "Brown",
    "Cyan",
    "Magenta",
    "Gold",
    "Silver",
    "Crimson",
    "Scarlet",
    "Ruby Red",
    "Wine Red",
    "Cherry Red",
    "Rose Pink",
    "Pastel Pink",
    "Hot Pink",
    "Baby Blue",
    "Sky Blue",
    "Ocean Blue",
    "Navy Blue",
    "Royal Blue",
    "Teal",
    "Turquoise",
    "Mint",
    "Emerald Green",
    "Forest Green",
    "Olive",
    "Lime",
    "Lavender",
    "Violet",
    "Lilac",
    "Indigo",
    "Midnight Purple",
    "Peach",
    "Coral",
    "Salmon",
    "Cream",
    "Ivory",
    "Beige",
    "Sand",
    "Chocolate Brown",
    "Coffee Brown",
    "Amber",
    "Bronze",
    "Copper",
    "Pearl White",
    "Snow White",
    "Ash Gray",
    "Charcoal",
    "Jet Black",
    "Obsidian",
    "Neon Green",
    "Neon Blue",
    "Neon Pink",
    "Neon Purple",
    "Glowing Cyan",
    "Galaxy Purple",
    "Space Black",
    "Moonlight Silver",
    "Sunset Orange",
    "Sunrise Gold",
    "Storm Gray",
    "Rain Blue",
    "Cloud White",
    "Ice Blue",
    "Frost White",
    "Frozen Cyan",
    "Lava Red",
    "Fire Orange",
    "Flame Yellow",
    "Poison Green",
    "Toxic Purple",
    "Blood Red",
    "Ghost White",
    "Shadow Black",
    "Dream Pink",
    "Cotton Candy",
    "Bubblegum Pink",
    "Strawberry Milk",
    "Matcha Green",
    "Sakura Pink",
    "Cherry Blossom",
    "Maple Red",
    "Bamboo Green",
    "Lotus Pink",
    "Ocean Mint",
    "Deep Sea Blue",
    "Jellyfish Cyan",
    "Crystal Blue",
    "Diamond White",
    "Amethyst Purple",
    "Ruby Pink",
    "Sapphire Blue",
    "Emerald Cyan",
    "Black & Gold",
    "White & Silver",
    "Red & Black",
    "Pink & White",
    "Blue & Gold",
    "Purple & Black",
    "Mint & Cream",
    "Sky Blue & White",
    "Wine Red & Gold",
    "Emerald & Black",
    "Peach & Beige",
    "Lavender & Silver",
    "Cyan & Purple",
    "Orange & Brown",
    "Gray & Blue",
    "Sakura Pink & White",
    "Ice Blue & Silver",
    "Cream & Chocolate",
    "Neon Pink & Black",
    "Galaxy Purple & Cyan",
  ];

  const personalities = [
    "Elegant",
    "Quiet",
    "Chaotic",
    "Cute",
    "Cold",
    "Mysterious",
    "Sleepy",
    "Energetic",
    "Greedy",
    "Gentle",
    "Obsessive",
    "Playful",
    "Smart",
    "Shy",
    "Loyal",
    "Kind",
    "Aggressive",
    "Calm",
    "Emotional",
    "Romantic",
    "Tsundere",
    "Yandere",
    "Kuudere",
    "Dandere",
    "Sadistic",
    "Masochistic",
    "Curious",
    "Carefree",
    "Serious",
    "Childish",
    "Immature",
    "Wise",
    "Manipulative",
    "Cunning",
    "Flirty",
    "Friendly",
    "Awkward",
    "Lazy",
    "Hardworking",
    "Perfectionist",
    "Clumsy",
    "Confident",
    "Cowardly",
    "Brave",
    "Heroic",
    "Villainous",
    "Jealous",
    "Possessive",
    "Protective",
    "Motherly",
    "Fatherly",
    "Lonely",
    "Melancholic",
    "Cheerful",
    "Optimistic",
    "Pessimistic",
    "Hopeless",
    "Dreamy",
    "Delusional",
    "Insane",
    "Hyperactive",
    "Silent",
    "Talkative",
    "Polite",
    "Rude",
    "Sarcastic",
    "Sassy",
    "Stoic",
    "Sensitive",
    "Innocent",
    "Corrupted",
    "Naive",
    "Street Smart",
    "Book Smart",
    "Overprotective",
    "Reckless",
    "Chaotic Good",
    "Chaotic Evil",
    "Lawful Good",
    "Lawful Evil",
    "Neutral",
    "Independent",
    "Dependent",
    "Attention-Seeking",
    "Secretive",
    "Paranoid",
    "Overthinking",
    "Impulsive",
    "Competitive",
    "Selfish",
    "Selfless",
    "Elegant but Dangerous",
    "Cute but Violent",
    "Cold but Caring",
    "Quiet but Crazy",
    "Emotionless",
    "Unpredictable",
    "Mature",
    "Narcissistic",
    "Obsessed with Beauty",
    "Obsessed with Power",
    "Obsessed with Knowledge",
    "Soft-Spoken",
    "Broken",
    "Traumatized",
    "Emotionally Unstable",
    "Fake Smile",
    "Chaotic Artist",
    "Night Owl",
    "Sunshine Personality",
    "Gloomy",
    "Pure-hearted",
    "Corrupt Noble",
    "Royal and Arrogant",
    "Mischievous",
    "Feral",
    "Wild",
    "Graceful",
    "Elegant Monster",
    "Dangerously Curious",
    "Protective but Toxic",
    "Emotionally Detached",
    "Overly Honest",
    "People Pleaser",
    "Passive Aggressive",
    "Smooth Talker",
    "Hopeless Romantic",
    "Drama Queen",
    "Crybaby",
    "Stubborn",
    "Rebellious",
    "Adventurous",
    "Fearless",
    "Timid",
    "Cynical",
    "Genius",
    "Chaotic Genius",
    "Airheaded",
    "Overconfident",
    "Gentle Giant",
    "Tiny but Aggressive",
    "Elegant and Calm",
    "Cold and Elegant",
    "Sweet but Manipulative",
    "Soft but Dangerous",
    "Quiet Observer",
    "Emotionally Empty",
    "Lovesick",
    "Devoted",
    "Overattached",
    "Unhinged",
    "Detached",
    "Broken Hero",
    "Tragic Villain",
    "Silent Guardian",
    "Sleep-Deprived",
    "Socially Awkward",
    "Attention Hungry",
    "Chaotic Gremlin",
    "Angel-like",
    "Demon-like",
    "Monster-like",
    "Cat-like",
    "Fox-like",
    "Puppy-like",
    "Snake-like",
    "Crow-like",
    "Elegant Royalty",
    "Fake Innocence",
    "Emotionally Soft",
    "Mentally Unstable",
    "Extremely Loyal",
    "Possessively Loyal",
    "Violently Protective",
    "Morally Gray",
    "Sad but Gentle",
    "Happy but Empty",
    "Beautiful but Terrifying",
    "Charming",
    "Magnetic",
    "Cold-Blooded",
    "Emotionally Intelligent",
    "Unstable Genius",
    "Untrustworthy",
    "Chaotic Neutral",
    "Reserved",
    "Wholesome",
    "Weird",
    "Cryptic",
    "Mysteriously Calm",
    "Dreamlike",
    "Softhearted",
    "Heartless",
    "Obsessively Loving",
    "Hopelessly Devoted",
  ];

  const clothing = [
    "Kimono",
    "Oversized Hoodie",
    "Suit",
    "Streetwear",
    "Lolita Dress",
    "Techwear",
    "School Uniform",
    "Fantasy Armor",
    "Cape",
    "Winter Coat",
    "Bandages",
    "Maid Dress",
    "Priest Robe",
    "Nun Outfit",
    "Military Uniform",
    "Samurai Armor",
    "Ninja Outfit",
    "Pirate Coat",
    "Knight Armor",
    "Royal Dress",
    "Royal Suit",
    "Victorian Dress",
    "Victorian Suit",
    "Gothic Dress",
    "Gothic Lolita",
    "Punk Jacket",
    "Leather Jacket",
    "Bomber Jacket",
    "Denim Jacket",
    "Fur Coat",
    "Trench Coat",
    "Raincoat",
    "Lab Coat",
    "Doctor Uniform",
    "Nurse Outfit",
    "Chef Outfit",
    "Waiter Uniform",
    "Idol Costume",
    "Magician Outfit",
    "Witch Dress",
    "Wizard Robe",
    "Mage Cloak",
    "Alchemist Coat",
    "Cyber Suit",
    "Spacesuit",
    "Steampunk Outfit",
    "Clockwork Armor",
    "Battle Dress",
    "Tactical Gear",
    "Sniper Outfit",
    "Assassin Cloak",
    "Spy Outfit",
    "Detective Coat",
    "Mafia Suit",
    "Yakuza Outfit",
    "Festival Yukata",
    "Hanfu",
    "Cheongsam",
    "Qipao",
    "Shrine Maiden Outfit",
    "Monk Robe",
    "Traditional Robe",
    "Ancient Armor",
    "Tribal Outfit",
    "Desert Robe",
    "Arctic Coat",
    "Jungle Hunter Outfit",
    "Explorer Outfit",
    "Safari Outfit",
    "Travel Cloak",
    "Fisherman Outfit",
    "Farmer Clothes",
    "Mechanic Uniform",
    "Blacksmith Outfit",
    "Bartender Outfit",
    "Dancer Costume",
    "Ballet Dress",
    "Opera Outfit",
    "Performer Outfit",
    "Circus Costume",
    "Jester Outfit",
    "Pajamas",
    "Sleepwear",
    "Lingerie Style Outfit",
    "Elegant Dress",
    "Casual Wear",
    "Formal Suit",
    "Business Outfit",
    "Office Wear",
    "Beachwear",
    "Swimsuit",
    "Sport Outfit",
    "Track Jacket",
    "Basketball Jersey",
    "Volleyball Uniform",
    "Tennis Outfit",
    "Martial Arts Gi",
    "Boxing Outfit",
    "Fencing Uniform",
    "Racing Suit",
    "Pilot Uniform",
    "Flight Jacket",
    "Sailor Uniform",
    "Captain Coat",
    "Admiral Outfit",
    "Post-Apocalyptic Outfit",
    "Scavenger Outfit",
    "Zombie Survivor Outfit",
    "Apron Dress",
    "Corset Dress",
    "Layered Fashion",
    "Loose Sweater",
    "Turtleneck",
    "Crop Top",
    "Off-Shoulder Shirt",
    "Long Skirt",
    "Mini Skirt",
    "Pleated Skirt",
    "Cargo Pants",
    "Baggy Pants",
    "Skinny Jeans",
    "Shorts",
    "Fishnet Stockings",
    "Thigh High Socks",
    "Leg Warmers",
    "Fingerless Gloves",
    "Arm Sleeves",
    "Neck Scarf",
    "Face Veil",
    "Half Mask Outfit",
    "Full Mask Outfit",
    "Fox Mask Costume",
    "Crow Feather Cloak",
    "Wolf Fur Cape",
    "Butterfly Dress",
    "Spider Silk Outfit",
    "Jellyfish Inspired Dress",
    "Shark Hoodie",
    "Cat Ear Hoodie",
    "Bunny Hoodie",
    "Dragon Scale Armor",
    "Phoenix Robe",
    "Unicorn Dress",
    "Angel Robe",
    "Demon Outfit",
    "Ghost Kimono",
    "Vampire Coat",
    "Werewolf Hunter Outfit",
    "Necromancer Robe",
    "Celestial Dress",
    "Galaxy Cloak",
    "Moonlight Dress",
    "Sun Priest Outfit",
    "Cloud-Themed Outfit",
    "Ocean-Themed Outfit",
    "Forest Spirit Outfit",
    "Flower-Themed Dress",
    "Crystal Armor",
    "Glass Dress",
    "Porcelain Doll Dress",
    "Paper Outfit",
    "Ink Painter Outfit",
    "Music-Themed Outfit",
    "Violin Performer Outfit",
    "Piano Concert Dress",
    "Street Punk Outfit",
    "Grunge Outfit",
    "Emo Fashion",
    "Y2K Fashion",
    "Retro 80s Outfit",
    "90s Anime Outfit",
    "Arcade Gamer Outfit",
    "Virtual Idol Outfit",
    "Glitchcore Outfit",
    "Dreamcore Outfit",
    "Weirdcore Outfit",
    "Fairycore Outfit",
    "Angelcore Outfit",
    "Cottagecore Outfit",
    "Royalcore Outfit",
    "Dark Academia Outfit",
    "Light Academia Outfit",
    "Soft Girl Outfit",
    "E-Girl Outfit",
    "E-Boy Outfit",
    "Minimalist Fashion",
    "Luxury Fashion",
    "Monochrome Outfit",
    "Pastel Fashion",
    "Neon Fashion",
    "Elegant Black Dress",
    "White Wedding Dress",
    "Funeral Outfit",
    "Battle Uniform",
    "Torn Clothes",
    "Oversized Shirt",
    "Long Hoodie",
    "High Collar Coat",
    "Cape with Fur",
    "Feathered Cloak",
    "Chain Accessories Outfit",
    "Ribbon Covered Dress",
    "Flower Crown Dress",
    "Golden Embroidered Outfit",
    "Silver Armor Dress",
    "Blood-Stained Outfit",
    "Burned Clothes",
    "Frozen Cloak",
    "Wet Clothing Style",
    "Transparent Raincoat",
    "Oversized Kimono",
    "Half Formal Outfit",
    "Sleeveless Coat",
    "Layered Robe",
    "Battle Maid Outfit",
    "Military Cape",
    "Dark Priest Outfit",
    "Cyber Ninja Outfit",
    "Tech Priest Outfit",
    "Steampunk Butler Outfit",
    "Clockwork Maid Outfit",
    "Royal Butler Outfit",
    "Ghost Bride Dress",
    "Spider Queen Dress",
    "Butterfly Princess Dress",
    "Moon Priestess Outfit",
    "Star Traveler Outfit",
    "Void Cultist Robe",
    "Rune Covered Cloak",
    "Ancient Relic Armor",
    "Mechanical Suit",
    "Holographic Outfit",
    "AI-Themed Outfit",
    "Android Uniform",
    "Robot Maid Outfit",
    "Synthetic Leather Outfit",
    "Combat Bodysuit",
    "Tactical Cloak",
    "Cyber Armor",
    "Digital Pattern Jacket",
    "Pixel-Themed Hoodie",
    "Arcane Robe",
    "Rune Armor",
    "Magic Academy Uniform",
    "Alchemy Uniform",
    "Fantasy School Outfit",
    "Demon General Armor",
    "Heavenly Robe",
    "Corrupted Priest Outfit",
    "Elegant Vampire Outfit",
    "Blood Moon Dress",
    "Festival Streetwear",
    "Luxury Kimono",
    "Ancient Chinese Robe",
    "Ancient Japanese Outfit",
    "Ancient Greek Toga",
    "Ancient Egyptian Outfit",
    "Temple Guardian Armor",
    "Sacred Shrine Outfit",
    "Knight Commander Armor",
    "Pirate Captain Coat",
    "Forest Witch Dress",
    "Desert Nomad Outfit",
    "Snow Hunter Outfit",
    "Deep Sea Outfit",
    "Bioluminescent Dress",
    "Toxic Scientist Outfit",
    "Radioactive Hazard Suit",
    "Shadow Assassin Outfit",
    "Light Guardian Outfit",
    "Chaos Cultist Outfit",
    "Dream Walker Outfit",
    "Nightmare Cloak",
    "Lace Dress",
    "Ribbon Outfit",
    "Pearl Decorated Dress",
    "Crystal Decorated Outfit",
    "Gold Trimmed Robe",
    "Silver Thread Kimono",
    "Ink Splattered Outfit",
    "Paint Covered Overalls",
    "Musician Streetwear",
    "Elegant Concert Suit",
    "Theater Costume",
    "Opera Mask Outfit",
    "Magic Performer Outfit",
    "Doll-Like Outfit",
    "Puppet Master Outfit",
    "Living Armor",
    "Spirit Cloak",
    "Soul-Themed Outfit",
    "Moonlit Kimono",
    "Starry Night Cloak",
    "Cloud Hoodie",
    "Rainy Day Outfit",
    "Sunflower Dress",
    "Rose-Themed Outfit",
    "Spider Lily Kimono",
    "Lotus Priest Outfit",
    "Sakura Dress",
    "Bamboo Pattern Kimono",
    "Fox Spirit Outfit",
    "Crow-Themed Outfit",
    "Snake Pattern Outfit",
    "Tiger Fur Coat",
    "Rabbit Pajamas",
    "Koi-Themed Kimono",
    "Jellyfish Dress",
    "Shark Streetwear",
    "Dragon Robe",
    "Phoenix Armor",
    "Butterfly Sleeves",
    "Cat Butler Outfit",
    "Wolf Hunter Outfit",
    "Deer Spirit Outfit",
    "Bat Collar Coat",
    "Scorpion Armor",
    "Moth-Themed Cloak",
    "Frog Raincoat",
    "Axolotl Hoodie",
    "Whale Ocean Robe",
    "Octopus Streetwear",
    "Mechanical Wings Outfit",
    "Halo Dress",
    "Broken Crown Outfit",
    "Chain Bound Cloak",
    "Floating Sleeve Dress",
    "Bandage Wrapped Outfit",
    "Cracked Armor",
    "Void-Touched Robe",
    "Astral Traveler Outfit",
    "Comet-Themed Cloak",
    "Meteor Armor",
    "Celestial Uniform",
    "Dreamy Pajamas",
    "Soft Winter Fashion",
    "Heavy Military Coat",
    "Elegant Ballroom Dress",
    "Fantasy Prince Outfit",
    "Fantasy Princess Dress",
    "Black Wedding Suit",
    "White Funeral Dress",
    "Corrupted Royal Outfit",
    "Ancient Mage Outfit",
    "Runic Cloak",
    "Storm Rider Coat",
    "Thunder Warrior Armor",
    "Lava Resistant Suit",
    "Ice Queen Dress",
    "Ocean Prince Outfit",
    "Forest Guardian Cloak",
    "Desert King Robe",
    "Galaxy Explorer Suit",
    "Space Pirate Outfit",
    "Cyber Idol Outfit",
    "Digital Witch Outfit",
    "Virtual Performer Outfit",
    "Mechanical Knight Armor",
    "Steam Engineer Outfit",
    "Clock Tower Butler Outfit",
    "Elegant Gothic Suit",
    "Pastel Idol Outfit",
    "Neon Punk Outfit",
    "Dark Royal Dress",
    "Soft Angel Outfit",
    "Cute Demon Hoodie",
    "Street Samurai Outfit",
    "Arcade Gamer Hoodie",
    "Pixel Art Jacket",
    "Retro Bomber Jacket",
    "Luxury Fur Cape",
    "Futuristic School Uniform",
    "Magical Girl Outfit",
    "Dark Magical Girl Outfit",
    "Moon Guardian Dress",
    "Sun Warrior Armor",
    "Star Idol Costume",
    "Cloud Traveler Cloak",
    "Dreamcore Sweater",
    "Weirdcore Outfit",
    "Fairytale Dress",
    "Ghostly Kimono",
    "Haunted Bride Dress",
    "Vampire Ballroom Outfit",
    "Royal Vampire Cape",
    "Zombie Survivor Hoodie",
    "Wasteland Armor",
    "Scavenger Streetwear",
    "Broken Uniform",
    "Overdecorated Royal Outfit",
    "Minimal White Outfit",
    "Elegant Monochrome Suit",
    "All Black Fashion",
    "All White Fashion",
    "Pastel Rainbow Outfit",
    "Silver Cyber Suit",
    "Golden Royal Armor",
    "Black & Red Gothic Outfit",
    "Blue & Gold Royal Dress",
    "Pink Idol Fashion",
    "Purple Witch Dress",
    "Green Forest Cloak",
    "Orange Festival Outfit",
    "Red Shrine Outfit",
    "White Priest Robe",
    "Dark Cultist Cloak",
    "Holy Knight Armor",
    "Fantasy Adventurer Outfit",
    "Traveler Streetwear",
    "Elegant Casual Outfit",
    "Soft Cottagecore Dress",
    "Cute Layered Fashion",
    "Oversized Fashion",
    "Tight Bodysuit",
    "Elegant Sleeveless Dress",
    "One-Eyed Mask Outfit",
    "Mechanical Tailcoat",
    "Chainmail Dress",
    "Fantasy Butler Outfit",
    "Rose Thorn Cloak",
    "Poison Queen Dress",
    "Deep Ocean Cloak",
    "Frost Covered Outfit",
    "Burning Flame Robe",
    "Thunder God Armor",
    "Ancient Dragon Robe",
    "Celestial Priest Outfit",
    "Void King Outfit",
    "Dream Eater Cloak",
    "Night Sky Dress",
    "Galaxy Printed Hoodie",
    "Moon & Stars Kimono",
    "Crow Feather Jacket",
    "Fox Spirit Kimono",
    "Wolf Fur Armor",
    "Butterfly Fairy Dress",
  ];

  // ===== RANDOM FUNCTION =====

  const random = (arr: string[]) => arr[Math.floor(Math.random() * arr.length)];

  // ===== RANDOM MODE =====

  const randomMode = () => ({
    animal: random(animals),
    theme: random(themes),
    object: random(objects),
    color: random(colors),
    personality: random(personalities),
    clothing: random(clothing),
  });

  // ===== SMART MATCH MODE =====

  const smartThemes: any = {
    Fox: ["Japanese", "Yokai", "Forest Spirit"],
    Wolf: ["Dark Fantasy", "Forest Spirit", "Mythology"],
    Cat: ["Witchcore", "Dreamcore", "Fairycore"],
    Dog: ["Cottagecore", "Festival", "Nature"],
    Rabbit: ["Fairy", "Dreamcore", "Cottagecore"],
    Crow: ["Horror", "Vintage", "Gothic"],
    Raven: ["Horror", "Voidcore", "Lovecraftian"],
    Sparrow: ["Nature", "Festival", "Light Fantasy"],
    Owl: ["Mystic", "Nightmare", "Witchcore"],
    Hawk: ["Sky Kingdom", "Military", "Nature"],
    Eagle: ["Sky Kingdom", "Royal", "Military"],
    Falcon: ["Military", "Sky Kingdom", "Steampunk"],
    Peacock: ["Royal", "Luxury", "Festival"],
    Swan: ["Royalcore", "Fairytale", "Light Fantasy"],
    Duck: ["Cottagecore", "Nature", "Festival"],
    Goose: ["Festival", "Nature", "Cottagecore"],
    Chicken: ["Farm", "Cottagecore", "Festival"],
    Rooster: ["Festival", "Royal", "Nature"],
    Turkey: ["Festival", "Cottagecore", "Nature"],
    Pigeon: ["Urban", "Street Fashion", "Vintage"],
    Seagull: ["Ocean", "Street Punk", "Nature"],
    Penguin: ["Arctic", "Cottagecore", "Cute"],
    Parrot: ["Pirate", "Tropical", "Festival"],
    Cockatoo: ["Tropical", "Festival", "Luxury"],
    Flamingo: ["Pastel", "Luxury", "Festival"],
    Crane: ["Ancient Japan", "Elegant", "Nature"],
    Heron: ["Nature", "Ocean", "Mystic"],
    Stork: ["Fairytale", "Sky Kingdom", "Nature"],
    Kiwi: ["Cottagecore", "Nature", "Cute"],
    Cassowary: ["Jungle", "Dark Fantasy", "Nature"],
    Ostrich: ["Desert", "Nature", "Comedy"],
    Bat: ["Horror", "Nightmare", "Gothic"],
    Butterfly: ["Fairy", "Dreamcore", "Light Fantasy"],
    Moth: ["Voidcore", "Horror", "Dreamcore"],
    Bee: ["Nature", "Cottagecore", "Festival"],
    Wasp: ["Toxic", "Nature", "Horror"],
    Hornet: ["Toxic", "Military", "Nature"],
    Ant: ["Nature", "Cottagecore", "Military"],
    Spider: ["Horror", "Gothic", "Voidcore"],
    Scorpion: ["Desert", "Toxic", "Horror"],
    Dragonfly: ["Fairy", "Nature", "Dreamcore"],
    Grasshopper: ["Nature", "Cottagecore", "Festival"],
    Cricket: ["Nature", "Vintage", "Cottagecore"],
    Beetle: ["Mechanical", "Nature", "Steampunk"],
    Ladybug: ["Cute", "Fairy", "Nature"],
    Firefly: ["Fairy", "Dreamcore", "Bioluminescent"],
    Centipede: ["Horror", "Toxic", "Voidcore"],
    Millipede: ["Nature", "Toxic", "Horror"],
    Snail: ["Cottagecore", "Dreamcore", "Nature"],
    Slug: ["Voidcore", "Toxic", "Horror"],
    Jellyfish: ["Ocean", "Dreamcore", "Ghost"],
    Octopus: ["Ocean", "Mystic", "Lovecraftian"],
    Squid: ["Ocean", "Lovecraftian", "Mystic"],
    Cuttlefish: ["Ocean", "Bioluminescent", "Mystic"],
    Seal: ["Arctic", "Cottagecore", "Cute"],
    "Sea Lion": ["Ocean", "Festival", "Cute"],
    Walrus: ["Arctic", "Nature", "Vintage"],
    Dolphin: ["Ocean", "Light Fantasy", "Dreamcore"],
    Whale: ["Ocean", "Mystic", "Voidcore"],
    Shark: ["Ocean", "Cyberpunk", "Horror"],
    "Hammerhead Shark": ["Ocean", "Cyberpunk", "Toxic"],
    "Tiger Shark": ["Ocean", "Horror", "Wild"],
    "Great White Shark": ["Ocean", "Horror", "Military"],
    Manta: ["Ocean", "Dreamcore", "Light Fantasy"],
    Stingray: ["Ocean", "Mystic", "Dark Fantasy"],
    Swordfish: ["Ocean", "Military", "Royal"],
    Tuna: ["Ocean", "Nature", "Festival"],
    Salmon: ["Ocean", "Nature", "Cottagecore"],
    Koi: ["Ancient Japan", "Royal", "Festival"],
    Goldfish: ["Cute", "Dreamcore", "Fairy"],
    Catfish: ["Ocean", "Mystic", "Vintage"],
    Pufferfish: ["Ocean", "Cute", "Toxic"],
    Eel: ["Ocean", "Voidcore", "Mystic"],
    Seahorse: ["Ocean", "Fairy", "Dreamcore"],
    Clownfish: ["Ocean", "Cute", "Festival"],
    Otter: ["Cottagecore", "Cute", "Nature"],
    Beaver: ["Nature", "Cottagecore", "Military"],
    Raccoon: ["Street Fashion", "Urban", "Cottagecore"],
    Panda: ["Cottagecore", "Cute", "Nature"],
    "Red Panda": ["Cottagecore", "Cute", "Dreamcore"],
    Bear: ["Wild", "Nature", "Mythology"],
    "Polar Bear": ["Arctic", "Voidcore", "Nature"],
    "Grizzly Bear": ["Wild", "Forest Spirit", "Horror"],
    Koala: ["Cute", "Cottagecore", "Nature"],
    Sloth: ["Dreamcore", "Cottagecore", "Nature"],
    Monkey: ["Jungle", "Festival", "Chaos"],
    Chimpanzee: ["Jungle", "Nature", "Mystic"],
    Gorilla: ["Wild", "Military", "Nature"],
    Tiger: ["Royal", "Wild", "Fantasy"],
    Lion: ["Royal", "Mythology", "Desert"],
    Leopard: ["Wild", "Luxury", "Jungle"],
    Deer: ["Forest Spirit", "Fairy", "Nature"],
    Elk: ["Forest Spirit", "Mythology", "Nature"],
    Moose: ["Arctic", "Nature", "Mythology"],
    Horse: ["Royal", "Fantasy", "Military"],
    Zebra: ["Monochrome", "Wild", "Nature"],
    Camel: ["Desert", "Ancient Egypt", "Nature"],
    Elephant: ["Royal", "Mythology", "Nature"],
    Giraffe: ["Jungle", "Dreamcore", "Nature"],
    Kangaroo: ["Desert", "Festival", "Nature"],
    Hippo: ["River", "Nature", "Cute"],
    Rhino: ["Military", "Wild", "Nature"],
    Crocodile: ["Swamp", "Horror", "Nature"],
    Alligator: ["Swamp", "Horror", "Military"],
    Snake: ["Horror", "Mythology", "Toxic"],
    Cobra: ["Royal", "Horror", "Mythology"],
    Frog: ["Nature", "Fairy", "Cottagecore"],
    Toad: ["Horror", "Witchcore", "Nature"],
    Axolotl: ["Dreamcore", "Cute", "Mystic"],
    Phoenix: ["Mythology", "Fire", "Royal"],
    Dragon: ["Fantasy", "Mythology", "Royal"],
    Unicorn: ["Fairy", "Light Fantasy", "Royal"],
    Griffin: ["Mythology", "Royal", "Fantasy"],
    Kraken: ["Ocean", "Lovecraftian", "Horror"],
    Mermaid: ["Ocean", "Fairy", "Dreamcore"],
    Kitsune: ["Japanese", "Yokai", "Mystic"],
    Tanuki: ["Japanese", "Festival", "Chaos"],
    Yeti: ["Arctic", "Mythology", "Horror"],
    "Loch Ness Monster": ["Mystic", "Ocean", "Mythology"],
  };

  const smartObjects: any = {
    Japanese: [
      "Fox Mask",
      "Kitsune Mask",
      "Paper Umbrella",
      "Lantern",
      "Fan",
      "Kimono Sleeve",
      "Torii Gate",
      "Shrine Charm",
      "Katana",
      "Ink Bottle",
    ],
    Cyberpunk: [
      "Cyber Chip",
      "Hologram",
      "Neon Tube",
      "Glitch Screen",
      "VR Headset",
      "AI Core",
      "USB Drive",
      "Data Disk",
      "Mechanical Arm",
    ],
    Dreamcore: [
      "Dreamcatcher",
      "Dream Mirror",
      "Floating Book",
      "Dream Bottle",
      "Galaxy Jar",
      "Cloud Pillow",
      "Snow Globe",
    ],
    Fantasy: [
      "Magic Scroll",
      "Rune Stone",
      "Crystal Ball",
      "Crystal Sword",
      "Dragon Egg",
      "Unicorn Horn",
      "Phoenix Feather",
    ],
    Ocean: [
      "Aquarium",
      "Ocean Bottle",
      "Pearl",
      "Coral",
      "Seahorse",
      "Jellyfish Lamp",
      "Shark Tooth",
      "Anchor",
    ],
    Royal: [
      "Crown",
      "Golden Crown",
      "Royal Cape",
      "Sword",
      "Shield",
      "Necklace",
      "Ring",
      "Medal",
      "Throne",
    ],
    Nature: [
      "Bamboo",
      "Acorn",
      "Maple Leaf",
      "Plant Pot",
      "Bonsai",
      "Feather",
      "Flower Vase",
    ],
    Festival: [
      "Festival Lantern",
      "Wind Chime",
      "Bell",
      "Pinwheel",
      "Mask",
      "Paper Crane",
      "Confetti",
    ],
    Horror: [
      "Skull",
      "Bone",
      "Candle",
      "Ghost Candle",
      "Cracked Mask",
      "Blood Stain",
      "Broken Sword",
    ],
    Space: [
      "Planet",
      "Galaxy",
      "Meteor",
      "Comet",
      "Satellite",
      "Spaceship",
      "Star",
      "Moon",
    ],
    Vintage: [
      "Pocket Watch",
      "Typewriter",
      "Cassette",
      "Film Reel",
      "Diary",
      "Old Photo",
      "Radio",
    ],
    Steampunk: [
      "Clockwork Gear",
      "Steam Engine",
      "Steam Pipe",
      "Steampunk Goggles",
      "Mechanical Arm",
      "Valve",
    ],
    Yokai: [
      "Kitsune Mask",
      "Spirit Lantern",
      "Charm",
      "Talisman",
      "Paper Crane",
      "Fox Mask",
    ],
    StreetFashion: [
      "Sunglasses",
      "Neon Sign",
      "Chains",
      "Phone",
      "Headphones",
      "Backpack",
    ],
    Angel: ["Halo", "White Feather", "Light Halo", "Prayer Beads"],
    Demon: ["Black Feather", "Chain", "Broken Sword", "Skull"],
    Fairy: [
      "Crystal Flower",
      "Butterfly Pin",
      "Fairy Light",
      "Wind Bell",
      "Flower Crown",
    ],
    Ghost: [
      "Ghost Candle",
      "Mirror",
      "Bell",
      "Lantern",
      "Paper",
      "Floating Book",
    ],
    PostApocalyptic: [
      "Gas Mask",
      "Broken Mask",
      "Scrap Metal",
      "Battery",
      "Radio",
    ],
    SciFi: ["Laser Gun", "Drone", "AI Core", "Cyber Chip", "Hologram"],
    Medieval: ["Shield", "Sword", "Helmet", "Armor", "Crown"],
    Victorian: ["Pocket Watch", "Cane", "Teacup", "Mirror", "Diary"],
    Gothic: ["Candle", "Skull", "Rose", "Chain", "Mirror"],
    DarkFantasy: ["Crystal Sword", "Shadow Cloak", "Bone Crown", "Rune Stone"],
    LightFantasy: [
      "Crystal Flower",
      "Light Halo",
      "Fairy Light",
      "Star Pendant",
    ],
    Mythology: ["Ancient Tablet", "Talisman", "Relic", "Rune Stone", "Statue"],
    AncientEgypt: ["Scarab", "Golden Mask", "Ancient Tablet", "Seal Stamp"],
    AncientGreece: ["Statue", "Laurel Crown", "Scroll", "Column Fragment"],
    AncientChina: ["Fan", "Scroll", "Ink Bottle", "Calligraphy Brush"],
    AncientJapan: ["Katana", "Torii Gate", "Lantern", "Kimono Sleeve"],
    Samurai: ["Katana", "Armor", "Helmet", "Banner"],
    Ninja: ["Kunai", "Shuriken", "Smoke Bomb", "Mask"],
    Pirate: ["Pirate Flag", "Treasure Chest", "Map", "Compass", "Hook"],
    Knight: ["Sword", "Shield", "Armor", "Helmet"],
    Circus: ["Balloon", "Mask", "Ticket", "Bell"],
    Carnival: ["Mask", "Ticket", "Confetti", "Lantern"],
    Casino: ["Dice", "Card", "Coin", "Chip"],
    Mafia: ["Gun", "Suitcase", "Chain", "Cigarette"],
    Detective: ["Magnifying Glass", "Notebook", "Camera", "Pipe"],
    Military: ["Gun", "Helmet", "Binoculars", "Radar"],
    Desert: ["Camel Figurine", "Sand Bottle", "Ancient Relic", "Sun Pendant"],
    Arctic: ["Snowflake", "Ice Cube", "Fur Coat", "Snow Globe"],
    Jungle: ["Bamboo", "Snake Idol", "Totem", "Leaf"],
    Underwater: ["Coral", "Pearl", "Sea Shell", "Fish Tank"],
    SkyKingdom: ["Cloud Ribbon", "Floating Island", "Wind Chime"],
    Cloudcore: ["Cloud Pillow", "Dream Bottle", "Feather"],
    Lovecraftian: ["Tentacle Relic", "Void Cube", "Ancient Book"],
    Witchcore: ["Potion Bottle", "Crystal Ball", "Magic Book", "Candle"],
    Fairytale: ["Magic Book", "Crown", "Flower", "Castle Key"],
    Fairycore: ["Butterfly Pin", "Flower Crown", "Fairy Light"],
    Kidcore: ["Toy", "Balloon", "Sticker", "Candy"],
    Weirdcore: ["Glitch Screen", "Broken Mask", "Eye Photo"],
    Voidcore: ["Void Cube", "Black Hole", "Shadow Orb"],
    Cottagecore: ["Basket", "Flower", "Tea Cup", "Bread"],
    Angelcore: ["Halo", "Feather", "Light Orb"],
    Devilcore: ["Chain", "Skull", "Red Flame"],
    Princesscore: ["Crown", "Dress", "Ring"],
    Royalcore: ["Golden Crown", "Royal Cape", "Ring"],
    Retro: ["Cassette", "Vinyl", "Old TV"],
    Neon80s: ["Neon Sign", "Tape", "Arcade Machine"],
    Anime90s: ["CD", "Poster", "VHS Tape"],
    Y2K: ["Flip Phone", "Sticker", "Glitter Bag"],
    Techwear: ["Mask", "Chain", "Utility Bag"],
    StreetPunk: ["Chains", "Graffiti Spray", "Boots"],
    Grunge: ["Broken Guitar", "Tape", "Smoked Glass"],
    Emo: ["Black Rose", "Chain", "Diary"],
    Pastel: ["Candy", "Ribbon", "Cute Plush"],
    Monochrome: ["Chess Piece", "Black White Photo"],
    Luxury: ["Diamond Ring", "Gold Watch", "Perfume"],
    Crystal: ["Crystal Ball", "Gem", "Prism"],
    Glass: ["Glass Eye", "Mirror", "Bottle"],
    Porcelain: ["Porcelain Doll", "Tea Cup"],
    Paper: ["Origami", "Paper Crane", "Scroll"],
    Ink: ["Ink Bottle", "Calligraphy Brush"],
    Music: ["Piano", "Violin", "Guitar", "Music Box"],
    Theater: ["Mask", "Curtain", "Script"],
    Opera: ["Mask", "Crown", "Music Sheet"],
    Idol: ["Microphone", "Light Stick", "Poster"],
    MagicAcademy: ["Magic Book", "Wand", "Potion"],
    Alchemy: ["Test Tube", "Potion Bottle", "Flask"],
    Necromancer: ["Skull", "Bone Staff", "Candle"],
    Celestial: ["Star Pendant", "Moon Necklace", "Galaxy"],
    Solar: ["Sun Pendant", "Light Orb"],
    Lunar: ["Moon Mirror", "Moon Clock"],
    Astrology: ["Star Compass", "Tarot Card"],
    Tarot: ["Tarot Card", "Crystal Ball"],
    Dreamwalker: ["Dream Mirror", "Dream Bottle"],
    Nightmare: ["Broken Mask", "Skull", "Candle"],
    Heaven: ["Halo", "Light Orb"],
    Hell: ["Chain", "Fire Flame", "Skull"],
    ForestSpirit: ["Totem", "Bamboo", "Spirit Charm"],
    DeepSea: ["Pearl", "Coral", "Sea Bottle"],
    Bioluminescent: ["Jellyfish Lamp", "Glow Orb"],
    Toxic: ["Poison Bottle", "Green Liquid"],
    Radioactive: ["Glowing Crystal", "Warning Sign"],
    Mechanical: ["Gear", "Robot Part"],
    Clockwork: ["Clock Gear", "Pocket Watch"],
    Digital: ["USB Drive", "Pixel Cube"],
    Glitch: ["Glitch Screen", "Broken Monitor"],
    VirtualReality: ["VR Headset", "Hologram"],
    Arcade: ["Game Controller", "Joystick"],
    Zombie: ["Bone", "Skull"],
    Vampire: ["Coffin Key", "Blood Bottle"],
    Werewolf: ["Wolf Fang", "Chain"],
    HauntedMansion: ["Candle", "Broken Mirror", "Door Key"],
  };
  const smartclothing: any = {
    Japanese: [
      "Kimono",
      "Festival Yukata",
      "Shrine Maiden Outfit",
      "Samurai Armor",
      "Fox Spirit Kimono",
      "Silver Thread Kimono",
    ],
    Cyberpunk: [
      "Cyber Suit",
      "Techwear Outfit",
      "Digital Pattern Jacket",
      "Holographic Outfit",
      "AI-Themed Outfit",
      "Cyber Armor",
    ],
    Dreamcore: [
      "Dreamcore Outfit",
      "Dream Walker Outfit",
      "Floating Sleeve Dress",
      "Cloud Hoodie",
      "Soft Sweater",
      "Weirdcore Outfit",
    ],
    Fantasy: [
      "Fantasy Armor",
      "Mage Cloak",
      "Wizard Robe",
      "Fantasy Princess Dress",
      "Ancient Mage Outfit",
      "Rune Armor",
    ],
    Ocean: [
      "Ocean-Themed Outfit",
      "Deep Sea Outfit",
      "Jellyfish Inspired Dress",
      "Whale Ocean Robe",
      "Sea Cape",
      "Bioluminescent Dress",
    ],
    Royal: [
      "Royal Dress",
      "Royal Suit",
      "Golden Embroidered Outfit",
      "Royal Cape",
      "Overdecorated Royal Outfit",
      "Blue & Gold Royal Dress",
    ],
    Nature: [
      "Cottagecore Dress",
      "Forest Guardian Cloak",
      "Flower-Themed Dress",
      "Soft Cottagecore Dress",
      "Nature Outfit",
      "Sunflower Dress",
    ],
    Festival: [
      "Festival Yukata",
      "Orange Festival Outfit",
      "Streetwear Festival Outfit",
      "Idol Costume",
      "Circus Costume",
      "Colorful Layered Fashion",
    ],
    Horror: [
      "Blood-Stained Outfit",
      "Gothic Dress",
      "Broken Uniform",
      "Haunted Bride Dress",
      "Nightmare Cloak",
      "Dark Cultist Cloak",
    ],
    Space: [
      "Spacesuit",
      "Galaxy Cloak",
      "Star Traveler Outfit",
      "Galaxy Printed Hoodie",
      "Astral Traveler Outfit",
      "Void King Outfit",
    ],
    Vintage: [
      "Victorian Dress",
      "Victorian Suit",
      "Retro 80s Outfit",
      "Old Fashion Coat",
      "Elegant Vintage Suit",
      "Classic Formal Dress",
    ],
    Steampunk: [
      "Steampunk Outfit",
      "Clockwork Maid Outfit",
      "Clock Tower Butler Outfit",
      "Mechanical Suit",
      "Steam Engineer Outfit",
      "Gear Armor",
    ],
    Yokai: [
      "Fox Spirit Kimono",
      "Ghost Kimono",
      "Shrine Outfit",
      "Spirit Cloak",
      "Traditional Robe",
      "Rune Covered Cloak",
    ],
    StreetFashion: [
      "Streetwear",
      "Oversized Hoodie",
      "Street Punk Outfit",
      "Shark Streetwear",
      "Traveler Streetwear",
      "Neon Punk Outfit",
    ],
    Angel: [
      "Angel Robe",
      "Soft Angel Outfit",
      "Halo Dress",
      "Heavenly Robe",
      "Light Guardian Outfit",
    ],
    Demon: [
      "Demon Outfit",
      "Dark Royal Dress",
      "Corrupted Priest Outfit",
      "Black & Red Gothic Outfit",
      "Chaos Cultist Outfit",
    ],
    Fairy: [
      "Fairycore Outfit",
      "Butterfly Fairy Dress",
      "Flower Crown Dress",
      "Light Fantasy Dress",
      "Crystal Decorated Outfit",
    ],
    Ghost: [
      "Ghost Kimono",
      "Ghostly Kimono",
      "White Funeral Dress",
      "Spirit Cloak",
      "Transparent Raincoat",
    ],
    PostApocalyptic: [
      "Wasteland Armor",
      "Scavenger Outfit",
      "Broken Uniform",
      "Torn Clothes",
      "Zombie Survivor Hoodie",
    ],
    SciFi: [
      "Mechanical Suit",
      "Cyber Suit",
      "AI-Themed Outfit",
      "Holographic Outfit",
      "Virtual Performer Outfit",
    ],
    Medieval: [
      "Knight Armor",
      "Battle Uniform",
      "Chainmail Dress",
      "Ancient Armor",
      "Holy Knight Armor",
    ],
    Victorian: [
      "Victorian Dress",
      "Elegant Suit",
      "Luxury Fur Cape",
      "Formal Suit",
      "Elegant Monochrome Suit",
    ],
    Gothic: [
      "Gothic Dress",
      "Elegant Gothic Suit",
      "Black Wedding Suit",
      "All Black Fashion",
      "Rose Thorn Cloak",
    ],
    DarkFantasy: [
      "Dark Magical Girl Outfit",
      "Void-Touched Robe",
      "Corrupted Royal Outfit",
      "Night Sky Dress",
    ],
    LightFantasy: [
      "Fairytale Dress",
      "Soft Angel Outfit",
      "Moonlight Dress",
      "Elegant Ballroom Dress",
    ],
    Mythology: [
      "Ancient Dragon Robe",
      "Golden Royal Armor",
      "Celestial Priest Outfit",
      "Rune Armor",
    ],
    AncientJapan: [
      "Kimono",
      "Shrine Maiden Outfit",
      "Samurai Armor",
      "Fox Spirit Kimono",
    ],
    Samurai: [
      "Samurai Armor",
      "Battle Uniform",
      "Heavy Military Coat",
      "Ancient Armor",
    ],
    Ninja: [
      "Ninja Outfit",
      "Cyber Ninja Outfit",
      "Shadow Assassin Outfit",
      "Half Mask Outfit",
    ],
    Pirate: [
      "Pirate Coat",
      "Pirate Captain Coat",
      "Traveler Streetwear",
      "Battle Uniform",
    ],
    Knight: [
      "Knight Armor",
      "Holy Knight Armor",
      "Chainmail Dress",
      "Battle Uniform",
    ],
    Military: [
      "Military Uniform",
      "Heavy Military Coat",
      "Tactical Gear",
      "Battle Uniform",
    ],
    Desert: [
      "Desert Robe",
      "Desert King Robe",
      "Explorer Outfit",
      "Nomad Outfit",
    ],
    Arctic: [
      "Winter Coat",
      "Arctic Coat",
      "Frost Covered Outfit",
      "Soft Winter Fashion",
    ],
    Jungle: ["Jungle Hunter Outfit", "Forest Guardian Cloak", "Safari Outfit"],
    Underwater: [
      "Ocean-Themed Outfit",
      "Deep Ocean Cloak",
      "Bioluminescent Dress",
    ],
    SkyKingdom: [
      "Cloud Hoodie",
      "Cloud Traveler Cloak",
      "Floating Sleeve Dress",
    ],
    Cloudcore: ["Cloud Hoodie", "Soft Sweater", "Dreamcore Sweater"],
    Lovecraftian: [
      "Void-Touched Robe",
      "Nightmare Cloak",
      "Dark Cultist Cloak",
    ],
    Witchcore: ["Witch Dress", "Forest Witch Dress", "Digital Witch Outfit"],
    Fairytale: [
      "Fairytale Dress",
      "Fantasy Princess Dress",
      "Elegant Ballroom Dress",
    ],
    Fairycore: [
      "Butterfly Fairy Dress",
      "Flower Crown Dress",
      "Soft Cottagecore Dress",
    ],
    Voidcore: ["Void-Touched Robe", "Chain Bound Cloak", "All Black Fashion"],
    Cottagecore: [
      "Soft Cottagecore Dress",
      "Flower-Themed Dress",
      "Casual Wear",
    ],
    Angelcore: ["Soft Angel Outfit", "Halo Dress", "Light Guardian Outfit"],
    Devilcore: [
      "Cute Demon Hoodie",
      "Dark Cultist Cloak",
      "Blood-Stained Outfit",
    ],
    Royalcore: [
      "Overdecorated Royal Outfit",
      "Golden Embroidered Outfit",
      "Royal Dress",
    ],
    Y2K: ["Y2K Fashion", "Neon Fashion", "Pixel Art Jacket"],
    Techwear: ["Techwear Outfit", "Cyber Armor", "Utility Jacket"],
    StreetPunk: ["Street Punk Outfit", "Neon Punk Outfit", "Grunge Outfit"],
    Grunge: ["Grunge Outfit", "Torn Clothes", "Broken Uniform"],
    Emo: ["Emo Fashion", "Black Gothic Outfit", "Chain Accessories Outfit"],
    Pastel: ["Pastel Fashion", "Soft Girl Outfit", "Cute Layered Fashion"],
    Monochrome: [
      "Monochrome Outfit",
      "Elegant Monochrome Suit",
      "All Black Fashion",
    ],
    Luxury: ["Luxury Fashion", "Golden Embroidered Outfit", "Luxury Fur Cape"],
    Crystal: ["Crystal Decorated Outfit", "Crystal Armor", "Crystal Dress"],
    Glass: ["Glass Dress", "Transparent Raincoat"],
    Porcelain: ["Porcelain Doll Dress", "Elegant Dress"],
    Ink: ["Ink Painter Outfit", "Ink Splattered Outfit"],
    Music: [
      "Music-Themed Outfit",
      "Musician Streetwear",
      "Elegant Concert Suit",
    ],
    Theater: ["Theater Costume", "Opera Outfit", "Mask Outfit"],
    Idol: ["Idol Costume", "Virtual Idol Outfit", "Cyber Idol Outfit"],
    MagicAcademy: ["Magic Academy Uniform", "Arcane Robe", "Alchemy Uniform"],
    Celestial: [
      "Celestial Dress",
      "Starry Night Cloak",
      "Moon Priestess Outfit",
    ],
    Solar: ["Sun Warrior Armor", "Sun Priest Outfit"],
    Lunar: ["Moonlight Dress", "Moon Guardian Dress"],
    Dreamwalker: ["Dream Walker Outfit", "Dreamcore Sweater"],
    Nightmare: ["Nightmare Cloak", "Broken Uniform"],
    Heaven: ["Heavenly Robe", "Soft Angel Outfit"],
    Hell: ["Burning Flame Robe", "Chaos Cultist Outfit"],
    ForestSpirit: ["Forest Guardian Cloak", "Green Forest Cloak"],
    DeepSea: ["Deep Ocean Cloak", "Ocean Prince Outfit"],
    Bioluminescent: ["Bioluminescent Dress"],
    Radioactive: ["Radioactive Hazard Suit"],
    Mechanical: ["Mechanical Suit", "Clockwork Maid Outfit"],
    Clockwork: ["Clockwork Outfit", "Steampunk Outfit"],
    Digital: ["Digital Pattern Jacket", "Pixel-Themed Hoodie"],
    Glitch: ["Glitchcore Outfit", "Broken Uniform"],
    VirtualReality: ["Virtual Performer Outfit", "Holographic Outfit"],
    Arcade: ["Arcade Gamer Outfit", "Arcade Gamer Hoodie"],
    Zombie: ["Zombie Survivor Hoodie", "Torn Clothes"],
    Vampire: ["Elegant Vampire Outfit", "Royal Vampire Cape"],
    Werewolf: ["Wolf Hunter Outfit", "Wolf Fur Armor"],
    HauntedMansion: ["Haunted Bride Dress", "Ghostly Kimono"],
  };

  const smartMode = () => {
    const animal = random(animals);

    const possibleThemes = smartThemes[animal] || themes;

    const theme = random(possibleThemes);

    const possibleObjects = smartObjects[theme] || objects;

    const possibleclothing = smartclothing[theme] || clothing;

    return {
      animal,
      theme,
      object: random(possibleObjects),
      color: random(colors),
      personality: random(personalities),
      clothing: random(possibleclothing),
    };
  };

  // ===== STATES =====

  const [result, setResult] = useState(randomMode());

  const [mode, setMode] = useState("random");

  const [saved, setSaved] = useState<any[]>([]);

  // ===== LOAD SAVED =====

  useEffect(() => {
    const storage = localStorage.getItem("savedCharacters");

    if (storage) {
      setSaved(JSON.parse(storage));
    }
  }, []);

  // ===== GENERATE =====

  const generate = () => {
    if (mode === "random") {
      setResult(randomMode());
    } else {
      setResult(smartMode());
    }
  };

  // ===== SAVE =====

  const saveResult = () => {
    const updated = [result, ...saved];

    setSaved(updated);

    localStorage.setItem("savedCharacters", JSON.stringify(updated));
  };

  // ===== DELETE =====

  const deleteSaved = (index: number) => {
    const updated = saved.filter((_, i) => i !== index);

    setSaved(updated);

    localStorage.setItem("savedCharacters", JSON.stringify(updated));
  };

  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#fff",
        color: "#000",
        fontFamily: "sans-serif",
        padding: "40px",
      }}
    >
      <div
        style={{
          maxWidth: "760px",
          margin: "0 auto",
        }}
      >
        {/* TITLE */}

        <h1
          style={{
            textAlign: "center",
            fontSize: "42px",
            marginBottom: "10px",
          }}
        >
          Character Generator
        </h1>

        <p
          style={{
            textAlign: "center",
            color: "#666",
            marginBottom: "40px",
          }}
        >
          OC idea randomizer made by toru_O
        </p>

        {/* MODE BUTTONS */}

        <div
          style={{
            display: "flex",
            gap: "12px",
            marginBottom: "24px",
          }}
        >
          <button
            onClick={() => setMode("random")}
            style={{
              ...modeButton,
              background: mode === "random" ? "#000" : "#fff",

              color: mode === "random" ? "#fff" : "#000",
            }}
          >
            Random Everything
          </button>

          <button
            onClick={() => setMode("smart")}
            style={{
              ...modeButton,
              background: mode === "smart" ? "#000" : "#fff",

              color: mode === "smart" ? "#fff" : "#000",
            }}
          >
            Smart Match
          </button>
        </div>

        {/* RESULT BOX */}

        <div
          style={{
            border: "1px solid #000",
            borderRadius: "28px",
            padding: "32px",
          }}
        >
          {Object.entries(result).map(([key, value]) => (
            <div
              key={key}
              style={{
                display: "flex",
                justifyContent: "space-between",

                padding: "14px 0",

                borderBottom: "1px solid #ddd",
              }}
            >
              <span
                style={{
                  fontWeight: "bold",
                  textTransform: "capitalize",
                }}
              >
                {key}
              </span>

              <span>{value}</span>
            </div>
          ))}

          {/* BUTTONS */}

          <div
            style={{
              display: "flex",
              gap: "12px",
              marginTop: "28px",
            }}
          >
            <button
              onClick={generate}
              style={{
                flex: 1,
                padding: "16px",
                borderRadius: "16px",
                border: "1px solid black",
                background: "#fff",
                cursor: "pointer",
                fontSize: "16px",
              }}
            >
              Generate
            </button>

            <button
              onClick={saveResult}
              style={{
                flex: 1,
                padding: "16px",
                borderRadius: "16px",
                border: "1px solid black",
                background: "#000",
                color: "#fff",
                cursor: "pointer",
                fontSize: "16px",
              }}
            >
              Save
            </button>
          </div>
        </div>

        {/* SAVED */}

        <div
          style={{
            marginTop: "50px",
          }}
        >
          <h2
            style={{
              marginBottom: "20px",
            }}
          >
            Saved Results
          </h2>

          {saved.length === 0 && (
            <p
              style={{
                color: "#777",
              }}
            >
              No saved results
            </p>
          )}

          <div
            style={{
              display: "grid",
              gap: "16px",
            }}
          >
            {saved.map((item, index) => (
              <div
                key={index}
                style={{
                  border: "1px solid #ddd",

                  borderRadius: "20px",

                  padding: "20px",

                  position: "relative",
                }}
              >
                <button
                  onClick={() => deleteSaved(index)}
                  style={{
                    position: "absolute",
                    top: "14px",
                    right: "14px",
                    border: "none",
                    background: "transparent",
                    cursor: "pointer",
                    fontSize: "18px",
                  }}
                >
                  ✕
                </button>

                <p>
                  <b>Animal:</b>{" "}
                  <a
                    href={`https://www.pinterest.com/search/pins/?q=${encodeURIComponent(
                      item.animal
                    )}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                      marginLeft: "100px",
                      color: "#E60023", // 👈 สีตัวหนังสือ
                      textDecoration: "none",
                    }}
                  >
                    {item.animal}
                  </a>
                </p>

                <p>
                  <b>Theme:</b>{" "}
                  <a
                    href={`https://www.pinterest.com/search/pins/?q=${encodeURIComponent(
                      item.theme
                    )}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                      marginLeft: "102px",
                      color: "#E60023", // 👈 สีตัวหนังสือ
                      textDecoration: "none",
                    }}
                  >
                    {item.theme}
                  </a>
                </p>

                <p>
                  <b>Object:</b>{" "}
                  <a
                    href={`https://www.pinterest.com/search/pins/?q=${encodeURIComponent(
                      item.object
                    )}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                      marginLeft: "103px",
                      color: "#E60023", // 👈 สีตัวหนังสือ
                      textDecoration: "none",
                    }}
                  >
                    {item.object}
                  </a>
                </p>

                <p>
                  <b>Color:</b>{" "}
                  <a
                    href={`https://www.pinterest.com/search/pins/?q=${encodeURIComponent(
                      item.color
                    )}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                      marginLeft: "114px",
                      color: "#E60023", // 👈 สีตัวหนังสือ
                      textDecoration: "none",
                    }}
                  >
                    {item.color}
                  </a>
                </p>

                <p>
                  <b> Personality:</b>{" "}
                  <a
                    href={`https://www.pinterest.com/search/pins/?q=${encodeURIComponent(
                      item.personality
                    )}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                      marginLeft: "65px",
                      color: "#E60023", // 👈 สีตัวหนังสือ
                      textDecoration: "none",
                    }}
                  >
                    {item.personality}
                  </a>
                </p>

                <p>
                  <b>Clothing:</b>{" "}
                  <a
                    href={`https://www.pinterest.com/search/pins/?q=${encodeURIComponent(
                      item.clothing
                    )}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                      marginLeft: "88px",
                      color: "#E60023", // 👈 สีตัวหนังสือ
                      textDecoration: "none",
                    }}
                  >
                    {item.clothing}
                  </a>
                </p>
                <a
                  href={`https://www.pinterest.com/search/pins/?q=${encodeURIComponent(
                    `${item.animal} ${item.object} ${item.theme} ${item.color} ${item.personality} ${item.clothing}`
                  )}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{
                    marginTop: "12px",
                    padding: "10px 14px",
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",

                    background: "#fff",
                    color: "#E60023",

                    border: "2px solid #E60023",
                    borderRadius: "50px",

                    fontWeight: "bold",
                    textDecoration: "none",

                    transition: "0.2s",
                  }}
                >
                  🔍 Search on Pinterest
                </a>
              </div>
            ))}
          </div>
        </div>

        {/* EXPLAIN */}

        <div
          style={{
            marginTop: "40px",
            color: "#666",
            lineHeight: 1.8,
          }}
        >
          <p>
            <b>Random Everything</b> = สุ่มทุกอย่างแบบอิสระ
          </p>

          <p>
            <b>Smart Match</b> = มีการจับคู่ theme/object ให้เข้ากับสัตว์มากขึ้น
          </p>
        </div>
      </div>
    </div>
  );
}

// ===== BUTTON STYLE =====

const modeButton = {
  flex: 1,
  padding: "14px",
  borderRadius: "14px",
  border: "1px solid black",
  cursor: "pointer",
  fontSize: "15px",
};
